### PR TITLE
[Feat] `Request::class` implement array access

### PR DESCRIPTION
**Pull request by SonyPradana**
- implement arrayaccess
- $query, $post as Collection
- support get input using __get
- new method query(), post()

### CODE REVIEW

**Comment by anggerpradana** [comment]
request is mutable or imutable now? 🤔

**Comment by SonyPradana** [comment]
> request is mutable or imutable now? 🤔

Request is mutable now, but only can access from array access

**Review by anggerpradana — CHANGES_REQUESTED** [review]
i think now can deprecated `getQuery()` and `getPost()`, because we have `query()` and `post()` method witch can return sama result.

**Comment by SonyPradana** [comment]
nice i will check it before, im alredy use it.

**Comment by SonyPradana** [comment]
> i think now can deprecated `getQuery()` and `getPost()`, because we have `query()` and `post()` method witch can return sama result.

is good idea, i will not deprecated soon. may after some other merge like API url.

**Comment by anggerpradana** [comment]
okey

**Review by anggerpradana — APPROVED** [review]

**Pull request merged**
