### PR TITLE
[Feat] Support Select Limit Using Offset (#46)

### PR DESCRIPTION
**Pull request by SonyPradana**
Reference (#46)

### CODE REVIEW

**Review by anggerpradana — CHANGES_REQUESTED** [review]
Need more test for real db test

**Comment by anggerpradana** [comment]
Will be nice if support offset without limit

**Comment by SonyPradana** [comment]
> Will be nice if support offset without limit

I dont known why, when hardcode  using only offset without limit will result error

**Comment by SonyPradana** [comment]
Need more information

[offset featch](https://www.sqlservertutorial.net/sql-server-basics/sql-server-offset-fetch/)

**Comment by SonyPradana** [comment]
This pr specific for limit offset, for advanced offset (eg  offset raws fetch) fill free to pr.

**Review by anggerpradana — APPROVED** [review]

**Pull request merged**
